pipeline {
    agent any

    environment {
        DOCKER_COMPOSE_FILE = 'docker-compose.yml'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the repository
                checkout scm
            }
        }
        stage('Load Environment Variables') {
            steps {
                script {
                    // Load environment variables from .env file
                    def envVars = readFile('.env').split('\n').collectEntries { line ->
                        def parts = line.split('=')
                        [(parts[0]): parts[1]]
                    }
                    envVars.each { key, value ->
                        env[key] = value
                    }
                }
            }
        }
        stage('Build and Deploy') {
            steps {
                script {
                    // Build and deploy the application using docker-compose
                    sh 'cd MyFavoriteImages-Backend && docker compose -f docker-compose.yml up -d --build'
                }
            }
        }
    }

    post {
        always {
            // Clean up the workspace
            cleanWs()
        }
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
